Restarted branch
Cg9291/Pokedex pull request #9
Opened 2023-10-24 17:52 UTC by Cg9291

Please don’t approve yet.
Just opened it so you guys can see the commits for now

2023-10-26 23:14 UTC, charlieldiaz commented on src/components/homepage/pokemonPictureCards/PokemonPictureCard.tsx
> +        typesArray.reverse().map((x: Type) => <PokemonTypesElement typeName={capitalizeWords(x.type.name)} />);
There is not unique key for What you are mapping. You must always add unique keys to react components to avoid rendering problems

2023-10-26 23:15 UTC, charlieldiaz commented on src/pages/Homepage.tsx
> +        randomPokemonSelection.map((i) => <PokemonPictureCard id={i} />);
Again, no unique Key, please see console logs . There are errors related to this.

2023-10-26 23:24 UTC, charlieldiaz requested changes
Please fix my comments. Pay attention to linter errors

2023-10-26 23:24 UTC, charlieldiaz commented on src/pages/Homepage.tsx
> +        randomPokemonSelection.map((i) => <PokemonPictureCard id={i} />);
Again, no unique Key, please see console logs . There are errors related to this.

2023-10-26 23:24 UTC, charlieldiaz commented on src/components/homepage/pokemonPictureCards/PokemonPictureCard.tsx
> +        typesArray.reverse().map((x: Type) => <PokemonTypesElement typeName={capitalizeWords(x.type.name)} />);
There is not unique key for What you are mapping. You must always add unique keys to react components to avoid rendering problems

2023-10-26 23:27 UTC, redlon23 reviewed
Also when you search for a pokemon with wrong name, we should show some generic error page rather than confusing the user

2023-10-27 17:31 UTC, Cg9291 commented
Ok,all these have now been fixed

2023-10-27 17:48 UTC, charlieldiaz approved these changes
Thank you for the changes

2023-10-27 17:52 UTC, merged